Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      -
        Label:
          default: "App Environment Configuration"
        Parameters:
          - ENVIRONMENT
          - CLASS
          - MinSize
          - MaxSize
          - DesiredCapacity
Parameters:
  CLASS:
    Type: String
    Description: Application Version to Deploy
    Default: "ITSE-1359-1001"
  STUDENTNAME:
    Type: String
    Description: Name of student (Ex - akroll)
    Default: "akroll"
  ENVIRONMENT:
    Type: String
    Description: Type of environment to provision
    Default: DEV
    AllowedValues:
      - DEV
      - TEST
      - PROD
      - PRESALES
Mappings:
  RegionMap:
    us-east-1:
      "AMALINUX" : "ami-c481fad3" # AMALINUX SEP 2016
    us-east-2:
      "AMALINUX" : "ami-71ca9114" # AMALINUX SEP 2016
    us-west-1:
      "AMALINUX" : "ami-de347abe" # AMALINUX SEP 2016
    us-west-2:
      "AMALINUX" : "ami-b04e92d0" # AMALINUX SEP 2016
    ca-central-1:
      "AMALINUX" : "ami-eb20928f" # AMALINUX SEP 2016 v01
    eu-west-1:
      "AMALINUX" : "ami-d41d58a7" # AMALINUX SEP 2016
    eu-central-1:
      "AMALINUX" : "ami-0044b96f" # AMALINUX SEP 2016
    eu-west-2:
      "AMALINUX" : "ami-bfe0eadb" # AMALINUX SEP 2016 v01
    ap-southeast-1:
      "AMALINUX" : "ami-7243e611" # AMALINUX SEP 2016
    ap-southeast-2:
      "AMALINUX" : "ami-663bdc04" # Windows Server 2016 OCT 2017
    ap-northeast-2:
      "AMALINUX" : "ami-a04297ce" # AMALINUX SEP 2016
    ap-northeast-1:
      "AMALINUX" : "ami-1a15c77b" # AMALINUX SEP 2016
    ap-south-1:
      "AMALINUX" : "ami-cacbbea5" # AMALINUX SEP 2016
    sa-east-1:
      "AMALINUX" : "ami-b777e4db" # AMALINUX SEP 2016
  InstanceSize:
    DEV:
      "EC2" : "t2.medium"
    TEST:
      "EC2" : "t2.micro"
    PROD:
      "EC2" : "t2.medium"
    PRESALES:
      "EC2" : "t2.micro"
Resources:
  AutoSubnetCustomResource:
    Type: "Custom::LambdaAutoSubnet" # or AWS::CloudFormation::CustomResource
    Properties:
      ServiceToken: !ImportValue sharedinf-autosubnetarn # The ARN of the lambda function - only mandatory property
      # "Provider Defined Properties" Below..
      DynamoDBRegion: !Ref "AWS::Region"
      DynamoDBTable: !ImportValue sharedinf-autosubnetddbtablename
      VPCCidr: !ImportValue sharedinf-vpciprange
      Debug: "True"
  SubnetPrivateA: # Public Subnet for App Env in AZ - A
    Type: "AWS::EC2::Subnet"
    Properties:
      AvailabilityZone: !Select [0, !GetAZs ]
      CidrBlock: !GetAtt AutoSubnetCustomResource.AppPublicCIDRA
      MapPublicIpOnLaunch: true
      VpcId: !ImportValue sharedinf-vpcid
  SubnetRouteTableAssociatePublicA: # Associates the subnet with a route table - passed via import
    DependsOn: SubnetPrivateA
    Type: "AWS::EC2::SubnetRouteTableAssociation"
    Properties:
      RouteTableId: !ImportValue sharedinf-privaterta
      SubnetId: !Ref SubnetPrivateA
  PrivateSG:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupName: !Join ["", [!Ref CLASS, "-", !Ref STUDENTNAME, "-", "PrivateSG"]]
      GroupDescription: !Join ["", [!Ref CLASS, "-", !Ref STUDENTNAME, "-", "PrivateSG", "  StackID: ", !Ref "AWS::StackId"]]
      VpcId: !ImportValue sharedinf-vpcid
      SecurityGroupIngress:
        -
          IpProtocol: tcp
          ToPort: "80"
          FromPort: "80"
          SourceSecurityGroupId: !ImportValue [!Join ["", [studentpublicsg, "-", !Ref STUDENTNAME]]]
        -
          SourceSecurityGroupId: !ImportValue [!Join ["", [studentpublicsg, "-", !Ref STUDENTNAME]]]
          IpProtocol: tcp
          ToPort: "3389"
          FromPort: "3389"
      SecurityGroupEgress:
        -
          SourceSecurityGroupId: !ImportValue [!Join ["", [studentpublicsg, "-", !Ref STUDENTNAME]]]
          ToPort: "-1"
          IpProtocol: "-1"
      Tags:
        -
          Key: Class
          Value: !Ref CLASS
        -
          Key: Name
          Value: !Ref STUDENTNAME
  EC2: # for now this is in a public subnet, needs to be changed.
    Type: "AWS::EC2::Instance"
    DeletionPolicy: Delete
    Properties:
      ImageId: !FindInMap [RegionMap, !Ref "AWS::Region", AMALINUX] # Dynamic mapping + Pseudo Parameter
      InstanceType: !FindInMap [InstanceSize, !Ref ENVIRONMENT, EC2]
      KeyName: !Join ["", [!Ref CLASS, "-", "KP", "-", !Ref STUDENTNAME]]
      SecurityGroupIds:
        - !Ref PrivateSG
      SubnetId: !Ref SubnetPrivateA
      Tags:
        -
          Key: Class
          Value: !Ref CLASS
        -
          Key: Name
          Value: !Ref STUDENTNAME